### ISSUE TITLE
Hello, can you update the function "forward_train()"?

### ISSUE THREAD

**Issue by LiGang1999** [seabearlmx/FSL#1]
The error is below:
&nbsp; &nbsp; File "/home/user/code/FSL-main/mmseg/models/segmentors/encoder_decoder.py", line 149, in _decode_head_forward_train
&nbsp; &nbsp; &nbsp; &nbsp; loss_decode, feats = self.decode_head.forward_train(x, img_metas,
TypeError: forward_train() got an unexpected keyword argument 'proto_feat'

**Comment by seabearlmx** [comment]
Thank you for your focus on our work! Since I have graduated, I can not test the code to ensure it is running right. You can follow the code in daformer_head.py to address this error.

In daformer_head.py:

lines 177 to 191 (feat_fusion function) correspond to Fig. 6 of the paper.

lines 194 to 206 (in forward function) can be used to offer an example to modify when using other decoders.

**Comment by wqq22** [comment]
> 错误如下：文件 “/home/user/code/FSL-main/mmseg/models/segmentors/encoder_decoder.py”，第 149 行，_decode_head_forward_trainloss_decode， feats = self.decode_head.forward_train（x， img_metas，TypeError：forward_train（） 收到了意外的关键字参数 'proto_feat'

请问你解决这个问题了吗

**Comment by LiGang1999** [comment]
> > 错误如下：文件 “/home/user/code/FSL-main/mmseg/models/segmentors/encoder_decoder.py”，第 149 行，_decode_head_forward_trainloss_decode， feats = self.decode_head.forward_train（x， img_metas，TypeError：forward_train（） 收到了意外的关键字参数 'proto_feat'
> 
> 请问你解决这个问题了吗

I have not, but you can try to resolve it.

**Comment by wqq22** [comment]
我解决了这个问题，但是后面还有其他很多的问题



---Original---
From: "Gang ***@***.***&gt;
Date: Sat, Apr 12, 2025 16:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [seabearlmx/FSL] Hello, can you update the function"forward_train()"? (Issue #1)


     
错误如下：文件 “/home/user/code/FSL-main/mmseg/models/segmentors/encoder_decoder.py”，第 149 行，_decode_head_forward_trainloss_decode， feats = self.decode_head.forward_train（x， img_metas，TypeError：forward_train（） 收到了意外的关键字参数 'proto_feat'
  
请问你解决这个问题了吗
  
I have not, but you can try to resolve it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  LiGang1999 left a comment (seabearlmx/FSL#1)
   
错误如下：文件 “/home/user/code/FSL-main/mmseg/models/segmentors/encoder_decoder.py”，第 149 行，_decode_head_forward_trainloss_decode， feats = self.decode_head.forward_train（x， img_metas，TypeError：forward_train（） 收到了意外的关键字参数 'proto_feat'
  
请问你解决这个问题了吗
  
I have not, but you can try to resolve it.

**Comment by seabearlmx** [comment]
谢谢您的关注！很抱歉，上传的这个代码版本似乎出了错误。由于我现在来了新单位，目前只有GitHub上这个版本的代码。如果您有任何问题的话都可以先提出来，我们一起讨论解决。后续暑假时间我可能会把代码重新整理调试好再更新过来。
